version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
      # - '443:443'
      # - '443:443/udp'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend

  frontend:
    container_name: "nextjs"
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
