version: '3.9'

services:
  nginx:
    container_name: nginx
    image: nginx
    ports:
      - '80:80'
      # - '443:443'
      # - '443:443/udp'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - backend

  frontend:
    container_name: "nextjs"
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  backend:
    container_name: "django"
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/media:/server/media
      - ./backend/static:/server/static
    depends_on:
      - database

  database:
    container_name: "postgres"
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
